// web/admin-panel/src/pages/crowdsec-stats/index.tsx
import { Card, Row, Col, Statistic, Space, Button, Typography, Empty, Tag, Alert } from "antd";
import { ReloadOutlined } from "@ant-design/icons";
import { useCustom } from "@refinedev/core";
import { useTranslation } from "react-i18next";
import { useMemo, useState, useEffect } from "react";

interface CrowdsecStats {
  total_decisions?: number;
  by_type?: Record<string, number>;
  by_scenario?: Record<string, number>;
  cache?: { hits: number; misses: number; hit_rate_pct: number };
}

const typeColor = (t_: string): string =>
  ({ ban: "red", captcha: "gold", throttle: "orange" }[t_] ?? "default");

export const CrowdsecStatsPage: React.FC = () => {
  const { t } = useTranslation();
  const [lastRefresh, setLastRefresh] = useState("—");

  const { result, query } = useCustom<CrowdsecStats>({
    url: "/api/crowdsec/stats",
    method: "get",
    queryOptions: { staleTime: 5_000, refetchInterval: 10_000 },
  });
  const refetch = query.refetch;
  const isLoading = query.isLoading;
  const isFetching = query.isFetching;
  const dataUpdatedAt = query.dataUpdatedAt;

  useEffect(() => {
    if (dataUpdatedAt) setLastRefresh(new Date(dataUpdatedAt).toLocaleTimeString());
  }, [dataUpdatedAt]);

  const stats = result?.data;

  const maxTypeCount = useMemo(() => {
    if (!stats?.by_type) return 1;
    return Math.max(...Object.values(stats.by_type), 1);
  }, [stats]);

  const topScenarios = useMemo(() => {
    if (!stats?.by_scenario) return [];
    return Object.entries(stats.by_scenario)
      .sort((a, b) => b[1] - a[1])
      .slice(0, 10);
  }, [stats]);

  return (
    <Space direction="vertical" size="middle" style={{ width: "100%" }}>
      <Space style={{ width: "100%", justifyContent: "space-between" }}>
        <Typography.Title level={4} style={{ margin: 0 }}>
          {t("crowdsec.statsTitle")}
        </Typography.Title>
        <Button icon={<ReloadOutlined spin={isFetching} />} onClick={() => refetch()} type="primary">
          {t("common.refresh")}
        </Button>
      </Space>

      {!stats?.total_decisions && !isLoading && (
        <Alert type="warning" message={t("crowdsec.notActive")} showIcon />
      )}

      <Row gutter={[12, 12]}>
        <Col xs={24} md={8}>
          <Card size="small">
            <Statistic title={t("crowdsec.cachedDecisions")} value={stats?.total_decisions ?? 0} valueStyle={{ color: "#1677ff" }} />
          </Card>
        </Col>
        <Col xs={24} md={8}>
          <Card size="small">
            <Statistic title={t("crowdsec.cacheHits")} value={stats?.cache?.hits ?? 0} valueStyle={{ color: "#52c41a" }} />
          </Card>
        </Col>
        <Col xs={24} md={8}>
          <Card size="small">
            <Statistic title={t("crowdsec.cacheHitRate")} value={stats?.cache?.hit_rate_pct ?? 0} precision={1} suffix="%" valueStyle={{ color: "#722ed1" }} />
          </Card>
        </Col>
      </Row>

      <Row gutter={[12, 12]}>
        <Col xs={24} md={12}>
          <Card size="small" title={t("crowdsec.byType")}>
            {!stats?.by_type || Object.keys(stats.by_type).length === 0 ? (
              <Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description={t("common.noData")} />
            ) : (
              <Space direction="vertical" size={6} style={{ width: "100%" }}>
                {Object.entries(stats.by_type).map(([type, count]) => (
                  <div key={type} style={{ display: "flex", alignItems: "center", gap: 8 }}>
                    <Tag color={typeColor(type)} style={{ width: 80, textAlign: "center", marginRight: 0 }}>{type}</Tag>
                    <div style={{ flex: 1, height: 8, background: "#f0f0f0", borderRadius: 4, overflow: "hidden" }}>
                      <div style={{ width: `${(count / maxTypeCount) * 100}%`, height: "100%", background: "#1677ff" }} />
                    </div>
                    <span style={{ width: 50, textAlign: "right", fontSize: 13 }}>{count}</span>
                  </div>
                ))}
              </Space>
            )}
          </Card>
        </Col>
        <Col xs={24} md={12}>
          <Card size="small" title={t("crowdsec.topScenarios")}>
            {topScenarios.length === 0 ? (
              <Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description={t("common.noData")} />
            ) : (
              <Space direction="vertical" size={4} style={{ width: "100%" }}>
                {topScenarios.map(([scenario, count]) => (
                  <div key={scenario} style={{ display: "flex", justifyContent: "space-between", fontSize: 13 }}>
                    <Typography.Text ellipsis style={{ maxWidth: 280 }} title={scenario}>{scenario}</Typography.Text>
                    <Typography.Text type="secondary">{count}</Typography.Text>
                  </div>
                ))}
              </Space>
            )}
          </Card>
        </Col>
      </Row>

      <Card size="small">
        <Space style={{ width: "100%", justifyContent: "space-between" }}>
          <Typography.Text type="secondary" style={{ fontSize: 12 }}>
            {stats?.total_decisions != null
              ? `${t("crowdsec.syncActive")} — ${stats.total_decisions} ${t("crowdsec.decisionsInCache")} (${stats.cache?.hits ?? 0} ${t("crowdsec.hits")} / ${stats.cache?.misses ?? 0} ${t("crowdsec.misses")})`
              : t("crowdsec.syncNotRunning")}
          </Typography.Text>
          <Typography.Text type="secondary" style={{ fontSize: 11 }}>
            {t("crowdsec.lastRefresh")} {lastRefresh}
          </Typography.Text>
        </Space>
      </Card>
    </Space>
  );
};

// web/admin-ui/src/views/CrowdSecStats.vue
<template>
  <Layout>
    <div class="p-6">
      <div class="flex items-center justify-between mb-6">
        <h2 class="text-2xl font-bold text-gray-800">{{ $t('crowdsec.stats.title') }}</h2>
        <button
          @click="load"
          class="px-3 py-1.5 text-sm bg-blue-600 text-white rounded hover:bg-blue-700"
        >
          {{ $t('common.refresh') }}
        </button>
      </div>

      <div v-if="!stats.total_decisions && !loading" class="bg-yellow-50 border border-yellow-200 rounded-lg p-4 mb-6">
        <span class="text-yellow-800">{{ $t('crowdsec.stats.notActive') }}
          <router-link to="/crowdsec-settings" class="underline">{{ $t('nav.settings') }}</router-link>.
        </span>
      </div>

      <!-- Top stat cards -->
      <div class="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6">
        <div class="bg-white rounded-lg shadow p-5">
          <div class="text-3xl font-bold text-blue-600">{{ stats.total_decisions ?? 0 }}</div>
          <div class="text-sm text-gray-500 mt-1">{{ $t('crowdsec.stats.cachedDecisions') }}</div>
        </div>
        <div class="bg-white rounded-lg shadow p-5">
          <div class="text-3xl font-bold text-green-600">{{ stats.cache?.hits ?? 0 }}</div>
          <div class="text-sm text-gray-500 mt-1">{{ $t('crowdsec.stats.cacheHits') }}</div>
        </div>
        <div class="bg-white rounded-lg shadow p-5">
          <div class="text-3xl font-bold text-purple-600">
            {{ stats.cache ? stats.cache.hit_rate_pct.toFixed(1) + '%' : '-' }}
          </div>
          <div class="text-sm text-gray-500 mt-1">{{ $t('crowdsec.stats.hitRate') }}</div>
        </div>
      </div>

      <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
        <!-- Decisions by type -->
        <div class="bg-white rounded-lg shadow p-5">
          <h3 class="font-semibold text-gray-700 mb-4">{{ $t('crowdsec.stats.byType') }}</h3>
          <div v-if="Object.keys(stats.by_type ?? {}).length === 0" class="text-gray-400 text-sm">{{ $t('common.noData') }}</div>
          <div v-else class="space-y-3">
            <div
              v-for="(count, type) in stats.by_type"
              :key="type"
              class="flex items-center gap-3"
            >
              <span
                :class="{
                  'bg-red-100 text-red-700': type === 'ban',
                  'bg-yellow-100 text-yellow-700': type === 'captcha',
                  'bg-orange-100 text-orange-700': type === 'throttle',
                  'bg-gray-100 text-gray-700': !['ban','captcha','throttle'].includes(String(type)),
                }"
                class="px-2 py-0.5 rounded text-xs font-medium w-20 text-center"
              >{{ type }}</span>
              <div class="flex-1 bg-gray-100 rounded-full h-2">
                <div
                  class="bg-blue-500 h-2 rounded-full"
                  :style="{ width: maxTypeCount > 0 ? (Number(count) / maxTypeCount * 100) + '%' : '0%' }"
                ></div>
              </div>
              <span class="text-sm font-medium text-gray-600 w-12 text-right">{{ count }}</span>
            </div>
          </div>
        </div>

        <!-- Top scenarios -->
        <div class="bg-white rounded-lg shadow p-5">
          <h3 class="font-semibold text-gray-700 mb-4">{{ $t('crowdsec.stats.topScenarios') }}</h3>
          <div v-if="topScenarios.length === 0" class="text-gray-400 text-sm">{{ $t('common.noData') }}</div>
          <div v-else class="space-y-2">
            <div
              v-for="[scenario, count] in topScenarios"
              :key="scenario"
              class="flex items-center justify-between"
            >
              <span class="text-sm text-gray-700 truncate max-w-xs" :title="scenario">{{ scenario }}</span>
              <span class="text-sm font-medium text-gray-500 ml-2">{{ count }}</span>
            </div>
          </div>
        </div>
      </div>

      <!-- Sync indicator -->
      <div class="mt-6 bg-white rounded-lg shadow p-4 flex items-center gap-3">
        <div class="w-2.5 h-2.5 rounded-full" :class="stats.total_decisions != null ? 'bg-green-400 animate-pulse' : 'bg-gray-300'"></div>
        <div class="text-sm text-gray-600">
          <span v-if="stats.total_decisions != null">
            {{ $t('crowdsec.stats.syncActive') }} — {{ stats.total_decisions }} {{ $t('crowdsec.stats.decisionsInCache') }}
            ({{ stats.cache?.hits ?? 0 }} {{ $t('crowdsec.stats.hits') }} / {{ stats.cache?.misses ?? 0 }} {{ $t('crowdsec.stats.misses') }})
          </span>
          <span v-else>{{ $t('crowdsec.stats.syncNotRunning') }}</span>
        </div>
        <div class="ml-auto text-xs text-gray-400">{{ $t('crowdsec.stats.lastRefresh') }} {{ lastRefresh }}</div>
      </div>
    </div>
  </Layout>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import axios from 'axios'
import Layout from '../components/Layout.vue'
import { useAuthStore } from '../stores/auth'

const auth = useAuthStore()

const stats = ref<any>({})
const loading = ref(false)
const lastRefresh = ref('-')

function headers() {
  return { Authorization: `Bearer ${auth.token}` }
}

const maxTypeCount = computed(() => {
  if (!stats.value.by_type) return 0
  return Math.max(...Object.values(stats.value.by_type as Record<string, number>), 1)
})

const topScenarios = computed(() => {
  if (!stats.value.by_scenario) return []
  return Object.entries(stats.value.by_scenario as Record<string, number>)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 10)
})

async function load() {
  loading.value = true
  try {
    const r = await axios.get('/api/crowdsec/stats', { headers: headers() })
    stats.value = r.data
    lastRefresh.value = new Date().toLocaleTimeString()
  } catch {
    // silent
  } finally {
    loading.value = false
  }
}

onMounted(load)
</script>
