// web/admin-panel/src/pages/notifications/index.tsx
import {
  Card,
  Button,
  Space,
  Table,
  Tag,
  Modal,
  Form,
  Input,
  Select,
  App,
  Typography,
  Popconfirm,
} from "antd";
import { PlusOutlined } from "@ant-design/icons";
import { useTable, useCreate, useDelete, useCustomMutation } from "@refinedev/core";
import type { ColumnsType } from "antd/es/table";
import { useTranslation } from "react-i18next";
import { useState } from "react";
import { fmtDateTime } from "../../utils/format";
import type { NotificationConfig } from "../../types/api";

interface NotifForm {
  name: string;
  channel_type: string;
  event_type: string;
  host_code?: string;
  config_json?: string;
}

const placeholderFor = (channel: string): string => {
  if (channel === "webhook") return '{"url": "https://hooks.example.com/..."}';
  if (channel === "telegram") return '{"bot_token": "...", "chat_id": "..."}';
  return '{"smtp_host": "smtp.gmail.com", "smtp_port": 587, "from": "waf@example.com", "to": ["admin@example.com"]}';
};

export const NotificationsPage: React.FC = () => {
  const { t } = useTranslation();
  const { message } = App.useApp();
  const [form] = Form.useForm<NotifForm>();
  const [open, setOpen] = useState(false);
  const [channel, setChannel] = useState("webhook");

  const { tableQuery, result } = useTable<NotificationConfig>({
    resource: "notifications",
    pagination: { mode: "off" },
    queryOptions: { staleTime: 30_000 },
  });
  const { mutate: create, mutation: createMutation } = useCreate();
  const { mutate: del } = useDelete();
  const { mutate: testNotif } = useCustomMutation();
  const creating = createMutation.isPending;

  const data = Array.isArray(result?.data) ? result.data : [];

  const onSubmit = async () => {
    const v = await form.validateFields();
    let cfg: unknown = {};
    try {
      cfg = JSON.parse(v.config_json ?? "{}");
    } catch {
      message.error("Invalid JSON config");
      return;
    }
    create(
      {
        resource: "notifications",
        values: {
          name: v.name,
          channel_type: v.channel_type,
          event_type: v.event_type,
          host_code: v.host_code,
          config_json: cfg,
        },
        successNotification: false,
      },
      {
        onSuccess: () => {
          message.success("OK");
          setOpen(false);
          form.resetFields();
          tableQuery.refetch();
        },
        onError: (err) => message.error(err.message),
      },
    );
  };

  const onDel = (id: string) =>
    del(
      { resource: "notifications", id, successNotification: false },
      {
        onSuccess: () => {
          message.success("OK");
          tableQuery.refetch();
        },
        onError: (err) => message.error(err.message),
      },
    );

  const onTest = (id: string) =>
    testNotif(
      { url: `/api/notifications/${id}/test`, method: "post", values: {} },
      {
        onSuccess: () => message.success(t("notifications.testSent")),
        onError: (err) => message.error(t("notifications.failed") + err.message),
      },
    );

  const columns: ColumnsType<NotificationConfig> = [
    { title: t("notifications.name"), dataIndex: "name" },
    { title: t("notifications.event"), dataIndex: "event_type" },
    { title: t("notifications.channel"), dataIndex: "channel_type", render: (v) => <Tag color="blue">{v}</Tag> },
    {
      title: t("notifications.lastTriggered"),
      dataIndex: "last_triggered",
      render: (v?: string) => (v ? fmtDateTime(v) : t("common.never")),
    },
    {
      title: "",
      key: "ops",
      width: 140,
      render: (_v, r) => (
        <Space>
          <Button size="small" type="link" onClick={() => onTest(r.id)}>
            {t("common.test")}
          </Button>
          <Popconfirm title={t("notifications.confirmDelete")} onConfirm={() => onDel(r.id)}>
            <Button size="small" type="link" danger>
              {t("common.delete")}
            </Button>
          </Popconfirm>
        </Space>
      ),
    },
  ];

  return (
    <Space direction="vertical" size="middle" style={{ width: "100%" }}>
      <Space style={{ width: "100%", justifyContent: "space-between" }}>
        <Typography.Title level={4} style={{ margin: 0 }}>
          {t("notifications.title")}
        </Typography.Title>
        <Button type="primary" icon={<PlusOutlined />} onClick={() => setOpen(true)}>
          {t("notifications.addConfig")}
        </Button>
      </Space>

      <Card size="small">
        <Table
          rowKey="id"
          size="small"
          dataSource={data}
          columns={columns}
          loading={tableQuery.isLoading}
          pagination={false}
          locale={{ emptyText: t("notifications.noConfigs") }}
        />
      </Card>

      <Modal
        title={t("notifications.newConfig")}
        open={open}
        onCancel={() => setOpen(false)}
        onOk={onSubmit}
        confirmLoading={creating}
        okText={t("common.create")}
        cancelText={t("common.cancel")}
        width={600}
        destroyOnClose
      >
        <Form
          form={form}
          layout="vertical"
          initialValues={{ channel_type: "webhook", event_type: "attack_detected", config_json: "{}" }}
          onValuesChange={(c) => c.channel_type && setChannel(c.channel_type)}
        >
          <Space.Compact style={{ width: "100%" }}>
            <Form.Item name="name" label={t("notifications.name")} rules={[{ required: true }]} style={{ flex: 1 }}>
              <Input />
            </Form.Item>
            <Form.Item name="channel_type" label={t("notifications.channel")} style={{ flex: 1 }}>
              <Select
                options={[
                  { value: "webhook", label: t("notifications.webhook") },
                  { value: "telegram", label: t("notifications.telegram") },
                  { value: "email", label: t("notifications.email") },
                ]}
              />
            </Form.Item>
          </Space.Compact>
          <Space.Compact style={{ width: "100%" }}>
            <Form.Item name="event_type" label={t("notifications.event")} style={{ flex: 1 }}>
              <Select
                options={[
                  { value: "attack_detected", label: t("notifications.attackDetected") },
                  { value: "cert_expiry", label: t("notifications.certExpiry") },
                  { value: "high_traffic", label: t("notifications.highTraffic") },
                  { value: "backend_down", label: t("notifications.backendDown") },
                ]}
              />
            </Form.Item>
            <Form.Item name="host_code" label={t("ccProtection.hostCode")} style={{ flex: 1 }}>
              <Input />
            </Form.Item>
          </Space.Compact>
          <Form.Item name="config_json" label={t("notifications.channelConfig")}>
            <Input.TextArea rows={5} placeholder={placeholderFor(channel)} style={{ fontFamily: "ui-monospace, monospace", fontSize: 12 }} />
          </Form.Item>
        </Form>
      </Modal>
    </Space>
  );
};

// web/admin-ui/src/views/Notifications.vue
<template>
  <Layout>
    <div class="p-6">
      <div class="flex items-center justify-between mb-6">
        <h2 class="text-xl font-semibold text-gray-800">{{ $t('notifications.title') }}</h2>
        <button @click="showForm = !showForm" class="btn-primary">{{ $t('notifications.addConfig') }}</button>
      </div>

      <!-- Form -->
      <div v-if="showForm" class="bg-white rounded-xl shadow-sm p-4 mb-6">
        <h3 class="text-sm font-semibold mb-3">{{ $t('notifications.newConfig') }}</h3>
        <div class="grid grid-cols-2 gap-3">
          <input v-model="form.name" :placeholder="$t('notifications.name')" class="input" />
          <select v-model="form.channel_type" class="input">
            <option value="webhook">{{ $t('notifications.webhook') }}</option>
            <option value="telegram">{{ $t('notifications.telegram') }}</option>
            <option value="email">{{ $t('notifications.email') }}</option>
          </select>
          <select v-model="form.event_type" class="input">
            <option value="attack_detected">{{ $t('notifications.attackDetected') }}</option>
            <option value="cert_expiry">{{ $t('notifications.certExpiry') }}</option>
            <option value="high_traffic">{{ $t('notifications.highTraffic') }}</option>
            <option value="backend_down">{{ $t('notifications.backendDown') }}</option>
          </select>
          <input v-model="form.host_code" :placeholder="$t('ccProtection.hostCode')" class="input" />
        </div>

        <!-- Channel config -->
        <div class="mt-3">
          <p class="text-xs font-medium text-gray-600 mb-1">{{ $t('notifications.channelConfig') }}</p>
          <textarea
            v-model="configJson"
            :placeholder="channelPlaceholder"
            class="w-full border border-gray-300 rounded-lg px-3 py-2 text-sm font-mono h-20 focus:outline-none focus:ring-2 focus:ring-blue-500"
          />
        </div>
        <div class="flex gap-2 mt-3">
          <button @click="createNotif" class="btn-primary text-sm">{{ $t('common.create') }}</button>
          <button @click="showForm = false" class="btn-secondary text-sm">{{ $t('common.cancel') }}</button>
        </div>
      </div>

      <!-- Table -->
      <div class="bg-white rounded-xl shadow-sm overflow-hidden">
        <table class="w-full text-sm">
          <thead class="bg-gray-50 border-b">
            <tr>
              <th class="text-left px-4 py-3 font-medium text-gray-600">{{ $t('notifications.name') }}</th>
              <th class="text-left px-4 py-3 font-medium text-gray-600">{{ $t('notifications.event') }}</th>
              <th class="text-left px-4 py-3 font-medium text-gray-600">{{ $t('notifications.channel') }}</th>
              <th class="text-left px-4 py-3 font-medium text-gray-600">{{ $t('notifications.lastTriggered') }}</th>
              <th class="px-4 py-3"></th>
            </tr>
          </thead>
          <tbody class="divide-y divide-gray-100">
            <tr v-for="n in notifs" :key="n.id" class="hover:bg-gray-50">
              <td class="px-4 py-3">{{ n.name }}</td>
              <td class="px-4 py-3 text-gray-600">{{ n.event_type }}</td>
              <td class="px-4 py-3">
                <span class="bg-blue-100 text-blue-700 text-xs px-2 py-0.5 rounded font-medium">{{ n.channel_type }}</span>
              </td>
              <td class="px-4 py-3 text-gray-400 text-xs">
                {{ n.last_triggered ? new Date(n.last_triggered).toLocaleString() : $t('common.never') }}
              </td>
              <td class="px-4 py-3 text-right space-x-2">
                <button @click="testNotif(n.id)" class="text-blue-500 hover:text-blue-700 text-xs">{{ $t('common.test') }}</button>
                <button @click="deleteNotif(n.id)" class="text-red-500 hover:text-red-700 text-xs">{{ $t('common.delete') }}</button>
              </td>
            </tr>
            <tr v-if="!notifs.length">
              <td colspan="5" class="px-4 py-6 text-center text-gray-400">{{ $t('notifications.noConfigs') }}</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </Layout>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { notifApi } from '../api'
import { useI18n } from 'vue-i18n'
import Layout from '../components/Layout.vue'

const { t } = useI18n()
const notifs = ref<any[]>([])
const showForm = ref(false)
const form = ref({ name: '', event_type: 'attack_detected', channel_type: 'webhook', host_code: '' })
const configJson = ref('{}')

const channelPlaceholder = computed(() => {
  if (form.value.channel_type === 'webhook') return '{"url": "https://hooks.example.com/..."}'
  if (form.value.channel_type === 'telegram') return '{"bot_token": "...", "chat_id": "..."}'
  return '{"smtp_host": "smtp.gmail.com", "smtp_port": 587, "from": "waf@example.com", "to": ["admin@example.com"]}'
})

async function load() {
  const r = await notifApi.list()
  notifs.value = r.data.data
}

async function createNotif() {
  let cfg = {}
  try { cfg = JSON.parse(configJson.value) } catch (_) {}
  await notifApi.create({ ...form.value, config_json: cfg })
  showForm.value = false
  load()
}

async function deleteNotif(id: string) {
  if (!confirm(t('notifications.confirmDelete'))) return
  await notifApi.delete(id)
  load()
}

async function testNotif(id: string) {
  try {
    await notifApi.test(id)
    alert(t('notifications.testSent'))
  } catch (e: any) {
    alert(t('notifications.failed') + (e.response?.data?.error || e.message))
  }
}

onMounted(load)
</script>

<style scoped>
.input { @apply border border-gray-300 rounded-md px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500; }
.btn-primary { @apply bg-blue-600 text-white px-4 py-2 rounded-md text-sm font-medium hover:bg-blue-700; }
.btn-secondary { @apply bg-white text-gray-700 border border-gray-300 px-4 py-2 rounded-md text-sm font-medium hover:bg-gray-50; }
</style>
